server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://onthego-database.cozyauqorjce.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: alsdud1~~
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # none, update, create, create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        time_zone: UTC
